### PR TITLE
Add basic structure and kanban board

### PR DESCRIPTION
**Pull request by imranhossainemi**
**Update the capstone JavaScript project** 

-Update kanban board
-update readme file

### CODE REVIEW

**Review by BregornOriginal — COMMENTED** [review]
## Hi @Team  

## While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### You have submitted a project, that doesn't have the following information

- The link that you need to submit on the request review should be a link to your GitHub Project, not to a Pull request
- Each card should have a student assigned

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by imranhossainemi** [comment]
>     * The link that you need to submit on the request review should be a link to your GitHub Project, not to a Pull request
Hello @BregornOriginal , It say pull request.
image

After Submitting the repo link it says this 

Untitled

**Comment by imranhossainemi** [comment]
>     * Each card should have a student assigned
How to edit kanban tasks?
 
image

**Review by AbayomiOlaoye — APPROVED** [review]
Hi @Team :wave:, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

applause

## Highlights
- Great implementation of reviewer's suggestions :heavy_check_mark: 
- All tasks assigned :heavy_check_mark: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
